// Re-export all types from frontend for consistency
export {
  Meal,
  DietDay,
  Patient,
  Role,
  Rasa,
  Virya,
  Guna,
  Vipaka,
  DoshaEffect,
  NutritionalData,
  AyurvedicProperties,
  FoodItem,
  MessMenuItem,
  MessMenu,
  DietPlan,
  Consultation,
  MealTracking,
  PatientFeedback,
  Vitals,
  User,
  Hospital,
  IFCFood,
  FoodSearchRequest,
  NutrientRangeRequest,
  Notification,
  NotificationType,
  NotificationSettings,
} from '../../../src/lib/types';