import Image from "next/image";
import { Card, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { BarChart, Bot, UtensilsCrossed } from "lucide-react";
import { PlaceHolderImages } from "@/lib/placeholder-images";

const features = [
  {
    icon: <UtensilsCrossed className="mb-4 h-8 w-8 text-primary" />,
    title: "AI Diet Generation",
    description: "Receive personalized Ayurvedic diet charts generated by our intelligent AI, tailored to your body type and health needs.",
    imageId: "feature-diet-chart",
  },
  {
    icon: <Bot className="mb-4 h-8 w-8 text-primary" />,
    title: "Personal Health Bot",
    description: "Get instant answers to your diet and health questions from a friendly AI chatbot, available 24/7.",
    imageId: "feature-chatbot",
  },
  {
    icon: <BarChart className="mb-4 h-8 w-8 text-primary" />,
    title: "Continuous Monitoring",
    description: "Track your progress, log meals, and provide feedback for dietitians to continuously optimize your health plan.",
    imageId: "feature-monitoring",
  },
];

export function FeaturesSection() {
  return (
    <section id="features" className="w-full py-12 md:py-24 lg:py-32 bg-secondary/50">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter font-headline sm:text-5xl">Features for a Balanced Life</h2>
            <p className="max-w-[900px] text-foreground/80 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              SolveAI provides a complete suite of tools to help you, your dietitian, and hospital staff manage your health journey seamlessly.
            </p>
          </div>
        </div>
        <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:gap-12 lg:max-w-none lg:grid-cols-3 pt-12">
          {features.map((feature, index) => {
            const featureImage = PlaceHolderImages.find(img => img.id === feature.imageId);
            return (
              <Card key={index} className="h-full transform hover:-translate-y-2 transition-transform duration-300 ease-in-out shadow-lg hover:shadow-2xl">
                <CardHeader className="items-center text-center">
                  {featureImage && (
                    <Image 
                      src={featureImage.imageUrl}
                      alt={feature.title}
                      width={600}
                      height={400}
                      data-ai-hint={featureImage.imageHint}
                      className="rounded-lg mb-4 aspect-video object-cover"
                    />
                  )}
                  {feature.icon}
                  <CardTitle className="font-headline">{feature.title}</CardTitle>
                  <CardDescription>{feature.description}</CardDescription>
                </CardHeader>
              </Card>
            );
          })}
        </div>
      </div>
    </section>
  );
}
